SELECT * FROM ARRIENDO_CAMION ORDER BY ID_CAMION ASC;

SELECT * FROM TIPO_SALUD ORDER BY COD_TIPO_SAL ASC;


SELECT * FROM ESTADO_CIVIL ORDER BY ID_ESTADO_CIVIL ASC;



SELECT COUNT(*) AS total_procesados FROM USUARIO_CLAVE;