CREATE USER SUMATIVA_2206_P1 IDENTIFIED BY "PRY2206sumativa_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER SUMATIVA_2206_P1  QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO SUMATIVA_2206_P1;
GRANT "RESOURCE" TO SUMATIVA_2206_P1;
ALTER USER SUMATIVA_2206_P1 DEFAULT ROLE "RESOURCE";